[package]
name = "conways-game-of-life"
version = "0.1.0"
authors = ["Ben Simmers"]
readme = "Readme.md"

[dependencies]
maplit = "*"

[lib]
name = "gollib"
path = "src/lib.rs"

[[bin]]
name = "game"
path = "src/main.rs"
